import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload: _payload, req: _req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
  CREATE TYPE "public"."_locales" AS ENUM('tr', 'en');
  CREATE TYPE "public"."enum_sections_type" AS ENUM('about', 'experience', 'projects', 'skills', 'education', 'hobbies', 'custom');
  CREATE TYPE "public"."enum_sections_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__sections_v_version_type" AS ENUM('about', 'experience', 'projects', 'skills', 'education', 'hobbies', 'custom');
  CREATE TYPE "public"."enum__sections_v_version_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__sections_v_published_locale" AS ENUM('tr', 'en');
  CREATE TYPE "public"."enum_experiences_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__experiences_v_version_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__experiences_v_published_locale" AS ENUM('tr', 'en');
  CREATE TYPE "public"."enum_projects_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__projects_v_version_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__projects_v_published_locale" AS ENUM('tr', 'en');
  CREATE TYPE "public"."enum_skill_groups_skills_color_key" AS ENUM('cyan', 'mint', 'violet', 'amber', 'rose', 'slate');
  CREATE TYPE "public"."enum_skill_groups_icon_key" AS ENUM('code', 'network', 'cloud', 'database', 'shield', 'activity', 'sparkles');
  CREATE TYPE "public"."enum_skill_groups_color_key" AS ENUM('cyan', 'mint', 'violet', 'amber', 'rose', 'slate');
  CREATE TYPE "public"."enum_skill_groups_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__skill_groups_v_version_skills_color_key" AS ENUM('cyan', 'mint', 'violet', 'amber', 'rose', 'slate');
  CREATE TYPE "public"."enum__skill_groups_v_version_icon_key" AS ENUM('code', 'network', 'cloud', 'database', 'shield', 'activity', 'sparkles');
  CREATE TYPE "public"."enum__skill_groups_v_version_color_key" AS ENUM('cyan', 'mint', 'violet', 'amber', 'rose', 'slate');
  CREATE TYPE "public"."enum__skill_groups_v_version_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__skill_groups_v_published_locale" AS ENUM('tr', 'en');
  CREATE TYPE "public"."enum_education_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__education_v_version_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__education_v_published_locale" AS ENUM('tr', 'en');
  CREATE TYPE "public"."enum_hobbies_icon_key" AS ENUM('book', 'camera', 'gamepad', 'music', 'plane', 'dumbbell', 'coffee');
  CREATE TYPE "public"."enum_hobbies_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__hobbies_v_version_icon_key" AS ENUM('book', 'camera', 'gamepad', 'music', 'plane', 'dumbbell', 'coffee');
  CREATE TYPE "public"."enum__hobbies_v_version_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__hobbies_v_published_locale" AS ENUM('tr', 'en');
  CREATE TYPE "public"."enum_profile_social_links_platform" AS ENUM('github', 'linkedin', 'email', 'website');
  CREATE TYPE "public"."enum_profile_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__profile_v_version_social_links_platform" AS ENUM('github', 'linkedin', 'email', 'website');
  CREATE TYPE "public"."enum__profile_v_version_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__profile_v_published_locale" AS ENUM('tr', 'en');
  CREATE TYPE "public"."enum_site_settings_default_language" AS ENUM('tr', 'en');
  CREATE TYPE "public"."enum_site_settings_language_switcher_position" AS ENUM('top-right', 'bottom-right');
  CREATE TYPE "public"."enum_site_settings_background_effect" AS ENUM('off', 'gradient', 'binary');
  CREATE TYPE "public"."enum_site_settings_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__site_settings_v_version_default_language" AS ENUM('tr', 'en');
  CREATE TYPE "public"."enum__site_settings_v_version_language_switcher_position" AS ENUM('top-right', 'bottom-right');
  CREATE TYPE "public"."enum__site_settings_v_version_background_effect" AS ENUM('off', 'gradient', 'binary');
  CREATE TYPE "public"."enum__site_settings_v_version_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__site_settings_v_published_locale" AS ENUM('tr', 'en');
  CREATE TABLE "users_sessions" ( "_order" integer NOT NULL, "_parent_id" integer NOT NULL, "id" varchar PRIMARY KEY NOT NULL, "created_at" timestamp(3) with time zone, "expires_at" timestamp(3) with time zone NOT NULL );
  CREATE TABLE "users" ( "id" serial PRIMARY KEY NOT NULL, "updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL, "created_at" timestamp(3) with time zone DEFAULT now() NOT NULL, "email" varchar NOT NULL, "reset_password_token" varchar, "reset_password_expiration" timestamp(3) with time zone, "salt" varchar, "hash" varchar, "reset_password_requested_at" timestamp(3) with time zone, "login_attempts" numeric DEFAULT 0, "lock_until" timestamp(3) with time zone );
  CREATE TABLE "media" ( "id" serial PRIMARY KEY NOT NULL, "alt" varchar NOT NULL, "updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL, "created_at" timestamp(3) with time zone DEFAULT now() NOT NULL, "url" varchar, "thumbnail_u_r_l" varchar, "filename" varchar, "mime_type" varchar, "filesize" numeric, "width" numeric, "height" numeric, "focal_x" numeric, "focal_y" numeric );
  CREATE TABLE "sections_legacy_anchors" ( "_order" integer NOT NULL, "_parent_id" integer NOT NULL, "_locale" "_locales" NOT NULL, "id" varchar PRIMARY KEY NOT NULL, "value" varchar );
  CREATE TABLE "sections" ( "id" serial PRIMARY KEY NOT NULL, "key" varchar, "type" "enum_sections_type", "enabled" boolean DEFAULT true, "show_in_navigation" boolean DEFAULT true, "order" numeric DEFAULT 0, "updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL, "created_at" timestamp(3) with time zone DEFAULT now() NOT NULL, "_status" "enum_sections_status" DEFAULT 'draft' );
  CREATE TABLE "sections_locales" ( "label" varchar, "anchor" varchar, "intro" varchar, "custom_content" jsonb, "id" serial PRIMARY KEY NOT NULL, "_locale" "_locales" NOT NULL, "_parent_id" integer NOT NULL );
  CREATE TABLE "_sections_v_version_legacy_anchors" ( "_order" integer NOT NULL, "_parent_id" integer NOT NULL, "_locale" "_locales" NOT NULL, "id" serial PRIMARY KEY NOT NULL, "value" varchar, "_uuid" varchar );
  CREATE TABLE "_sections_v" ( "id" serial PRIMARY KEY NOT NULL, "parent_id" integer, "version_key" varchar, "version_type" "enum__sections_v_version_type", "version_enabled" boolean DEFAULT true, "version_show_in_navigation" boolean DEFAULT true, "version_order" numeric DEFAULT 0, "version_updated_at" timestamp(3) with time zone, "version_created_at" timestamp(3) with time zone, "version__status" "enum__sections_v_version_status" DEFAULT 'draft', "created_at" timestamp(3) with time zone DEFAULT now() NOT NULL, "updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL, "snapshot" boolean, "published_locale" "enum__sections_v_published_locale", "latest" boolean );
  CREATE TABLE "_sections_v_locales" ( "version_label" varchar, "version_anchor" varchar, "version_intro" varchar, "version_custom_content" jsonb, "id" serial PRIMARY KEY NOT NULL, "_locale" "_locales" NOT NULL, "_parent_id" integer NOT NULL );
  CREATE TABLE "experiences_technologies" ( "_order" integer NOT NULL, "_parent_id" integer NOT NULL, "id" varchar PRIMARY KEY NOT NULL, "name" varchar );
  CREATE TABLE "experiences" ( "id" serial PRIMARY KEY NOT NULL, "key" varchar, "company" varchar, "start_date" timestamp(3) with time zone, "end_date" timestamp(3) with time zone, "is_current" boolean DEFAULT false, "company_url" varchar, "order" numeric DEFAULT 0, "updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL, "created_at" timestamp(3) with time zone DEFAULT now() NOT NULL, "_status" "enum_experiences_status" DEFAULT 'draft' );
  CREATE TABLE "experiences_locales" ( "role" varchar, "location" varchar, "summary" varchar, "id" serial PRIMARY KEY NOT NULL, "_locale" "_locales" NOT NULL, "_parent_id" integer NOT NULL );
  CREATE TABLE "_experiences_v_version_technologies" ( "_order" integer NOT NULL, "_parent_id" integer NOT NULL, "id" serial PRIMARY KEY NOT NULL, "name" varchar, "_uuid" varchar );
  CREATE TABLE "_experiences_v" ( "id" serial PRIMARY KEY NOT NULL, "parent_id" integer, "version_key" varchar, "version_company" varchar, "version_start_date" timestamp(3) with time zone, "version_end_date" timestamp(3) with time zone, "version_is_current" boolean DEFAULT false, "version_company_url" varchar, "version_order" numeric DEFAULT 0, "version_updated_at" timestamp(3) with time zone, "version_created_at" timestamp(3) with time zone, "version__status" "enum__experiences_v_version_status" DEFAULT 'draft', "created_at" timestamp(3) with time zone DEFAULT now() NOT NULL, "updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL, "snapshot" boolean, "published_locale" "enum__experiences_v_published_locale", "latest" boolean );
  CREATE TABLE "_experiences_v_locales" ( "version_role" varchar, "version_location" varchar, "version_summary" varchar, "id" serial PRIMARY KEY NOT NULL, "_locale" "_locales" NOT NULL, "_parent_id" integer NOT NULL );
  CREATE TABLE "projects_technologies" ( "_order" integer NOT NULL, "_parent_id" integer NOT NULL, "id" varchar PRIMARY KEY NOT NULL, "name" varchar );
  CREATE TABLE "projects" ( "id" serial PRIMARY KEY NOT NULL, "key" varchar, "image_id" integer, "live_url" varchar, "repository_url" varchar, "featured" boolean DEFAULT false, "order" numeric DEFAULT 0, "updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL, "created_at" timestamp(3) with time zone DEFAULT now() NOT NULL, "_status" "enum_projects_status" DEFAULT 'draft' );
  CREATE TABLE "projects_locales" ( "title" varchar, "summary" varchar, "role" varchar, "id" serial PRIMARY KEY NOT NULL, "_locale" "_locales" NOT NULL, "_parent_id" integer NOT NULL );
  CREATE TABLE "_projects_v_version_technologies" ( "_order" integer NOT NULL, "_parent_id" integer NOT NULL, "id" serial PRIMARY KEY NOT NULL, "name" varchar, "_uuid" varchar );
  CREATE TABLE "_projects_v" ( "id" serial PRIMARY KEY NOT NULL, "parent_id" integer, "version_key" varchar, "version_image_id" integer, "version_live_url" varchar, "version_repository_url" varchar, "version_featured" boolean DEFAULT false, "version_order" numeric DEFAULT 0, "version_updated_at" timestamp(3) with time zone, "version_created_at" timestamp(3) with time zone, "version__status" "enum__projects_v_version_status" DEFAULT 'draft', "created_at" timestamp(3) with time zone DEFAULT now() NOT NULL, "updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL, "snapshot" boolean, "published_locale" "enum__projects_v_published_locale", "latest" boolean );
  CREATE TABLE "_projects_v_locales" ( "version_title" varchar, "version_summary" varchar, "version_role" varchar, "id" serial PRIMARY KEY NOT NULL, "_locale" "_locales" NOT NULL, "_parent_id" integer NOT NULL );
  CREATE TABLE "skill_groups_skills" ( "_order" integer NOT NULL, "_parent_id" integer NOT NULL, "_locale" "_locales" NOT NULL, "id" varchar PRIMARY KEY NOT NULL, "name" varchar, "color_key" "enum_skill_groups_skills_color_key" );
  CREATE TABLE "skill_groups" ( "id" serial PRIMARY KEY NOT NULL, "key" varchar, "icon_key" "enum_skill_groups_icon_key", "color_key" "enum_skill_groups_color_key", "order" numeric DEFAULT 0, "updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL, "created_at" timestamp(3) with time zone DEFAULT now() NOT NULL, "_status" "enum_skill_groups_status" DEFAULT 'draft' );
  CREATE TABLE "skill_groups_locales" ( "title" varchar, "id" serial PRIMARY KEY NOT NULL, "_locale" "_locales" NOT NULL, "_parent_id" integer NOT NULL );
  CREATE TABLE "_skill_groups_v_version_skills" ( "_order" integer NOT NULL, "_parent_id" integer NOT NULL, "_locale" "_locales" NOT NULL, "id" serial PRIMARY KEY NOT NULL, "name" varchar, "color_key" "enum__skill_groups_v_version_skills_color_key", "_uuid" varchar );
  CREATE TABLE "_skill_groups_v" ( "id" serial PRIMARY KEY NOT NULL, "parent_id" integer, "version_key" varchar, "version_icon_key" "enum__skill_groups_v_version_icon_key", "version_color_key" "enum__skill_groups_v_version_color_key", "version_order" numeric DEFAULT 0, "version_updated_at" timestamp(3) with time zone, "version_created_at" timestamp(3) with time zone, "version__status" "enum__skill_groups_v_version_status" DEFAULT 'draft', "created_at" timestamp(3) with time zone DEFAULT now() NOT NULL, "updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL, "snapshot" boolean, "published_locale" "enum__skill_groups_v_published_locale", "latest" boolean );
  CREATE TABLE "_skill_groups_v_locales" ( "version_title" varchar, "id" serial PRIMARY KEY NOT NULL, "_locale" "_locales" NOT NULL, "_parent_id" integer NOT NULL );
  CREATE TABLE "education" ( "id" serial PRIMARY KEY NOT NULL, "key" varchar, "institution" varchar, "start_date" timestamp(3) with time zone, "end_date" timestamp(3) with time zone, "order" numeric DEFAULT 0, "updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL, "created_at" timestamp(3) with time zone DEFAULT now() NOT NULL, "_status" "enum_education_status" DEFAULT 'draft' );
  CREATE TABLE "education_locales" ( "program" varchar, "degree" varchar, "location" varchar, "description" varchar, "id" serial PRIMARY KEY NOT NULL, "_locale" "_locales" NOT NULL, "_parent_id" integer NOT NULL );
  CREATE TABLE "_education_v" ( "id" serial PRIMARY KEY NOT NULL, "parent_id" integer, "version_key" varchar, "version_institution" varchar, "version_start_date" timestamp(3) with time zone, "version_end_date" timestamp(3) with time zone, "version_order" numeric DEFAULT 0, "version_updated_at" timestamp(3) with time zone, "version_created_at" timestamp(3) with time zone, "version__status" "enum__education_v_version_status" DEFAULT 'draft', "created_at" timestamp(3) with time zone DEFAULT now() NOT NULL, "updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL, "snapshot" boolean, "published_locale" "enum__education_v_published_locale", "latest" boolean );
  CREATE TABLE "_education_v_locales" ( "version_program" varchar, "version_degree" varchar, "version_location" varchar, "version_description" varchar, "id" serial PRIMARY KEY NOT NULL, "_locale" "_locales" NOT NULL, "_parent_id" integer NOT NULL );
  CREATE TABLE "hobbies" ( "id" serial PRIMARY KEY NOT NULL, "key" varchar, "icon_key" "enum_hobbies_icon_key", "order" numeric DEFAULT 0, "updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL, "created_at" timestamp(3) with time zone DEFAULT now() NOT NULL, "_status" "enum_hobbies_status" DEFAULT 'draft' );
  CREATE TABLE "hobbies_locales" ( "title" varchar, "description" varchar, "id" serial PRIMARY KEY NOT NULL, "_locale" "_locales" NOT NULL, "_parent_id" integer NOT NULL );
  CREATE TABLE "_hobbies_v" ( "id" serial PRIMARY KEY NOT NULL, "parent_id" integer, "version_key" varchar, "version_icon_key" "enum__hobbies_v_version_icon_key", "version_order" numeric DEFAULT 0, "version_updated_at" timestamp(3) with time zone, "version_created_at" timestamp(3) with time zone, "version__status" "enum__hobbies_v_version_status" DEFAULT 'draft', "created_at" timestamp(3) with time zone DEFAULT now() NOT NULL, "updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL, "snapshot" boolean, "published_locale" "enum__hobbies_v_published_locale", "latest" boolean );
  CREATE TABLE "_hobbies_v_locales" ( "version_title" varchar, "version_description" varchar, "id" serial PRIMARY KEY NOT NULL, "_locale" "_locales" NOT NULL, "_parent_id" integer NOT NULL );
  CREATE TABLE "payload_kv" ( "id" serial PRIMARY KEY NOT NULL, "key" varchar NOT NULL, "data" jsonb NOT NULL );
  CREATE TABLE "payload_locked_documents" ( "id" serial PRIMARY KEY NOT NULL, "global_slug" varchar, "updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL, "created_at" timestamp(3) with time zone DEFAULT now() NOT NULL );
  CREATE TABLE "payload_locked_documents_rels" ( "id" serial PRIMARY KEY NOT NULL, "order" integer, "parent_id" integer NOT NULL, "path" varchar NOT NULL, "users_id" integer, "media_id" integer, "sections_id" integer, "experiences_id" integer, "projects_id" integer, "skill_groups_id" integer, "education_id" integer, "hobbies_id" integer );
  CREATE TABLE "payload_preferences" ( "id" serial PRIMARY KEY NOT NULL, "key" varchar, "value" jsonb, "updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL, "created_at" timestamp(3) with time zone DEFAULT now() NOT NULL );
  CREATE TABLE "payload_preferences_rels" ( "id" serial PRIMARY KEY NOT NULL, "order" integer, "parent_id" integer NOT NULL, "path" varchar NOT NULL, "users_id" integer );
  CREATE TABLE "payload_migrations" ( "id" serial PRIMARY KEY NOT NULL, "name" varchar, "batch" numeric, "updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL, "created_at" timestamp(3) with time zone DEFAULT now() NOT NULL );
  CREATE TABLE "profile_about_paragraphs" ( "_order" integer NOT NULL, "_parent_id" integer NOT NULL, "_locale" "_locales" NOT NULL, "id" varchar PRIMARY KEY NOT NULL, "text" varchar );
  CREATE TABLE "profile_social_links" ( "_order" integer NOT NULL, "_parent_id" integer NOT NULL, "id" varchar PRIMARY KEY NOT NULL, "platform" "enum_profile_social_links_platform", "url" varchar );
  CREATE TABLE "profile_social_links_locales" ( "label" varchar, "id" serial PRIMARY KEY NOT NULL, "_locale" "_locales" NOT NULL, "_parent_id" varchar NOT NULL );
  CREATE TABLE "profile" ( "id" serial PRIMARY KEY NOT NULL, "name" varchar, "_status" "enum_profile_status" DEFAULT 'draft', "updated_at" timestamp(3) with time zone, "created_at" timestamp(3) with time zone );
  CREATE TABLE "profile_locales" ( "job_title" varchar, "tagline" varchar, "resume_id" integer, "id" serial PRIMARY KEY NOT NULL, "_locale" "_locales" NOT NULL, "_parent_id" integer NOT NULL );
  CREATE TABLE "_profile_v_version_about_paragraphs" ( "_order" integer NOT NULL, "_parent_id" integer NOT NULL, "_locale" "_locales" NOT NULL, "id" serial PRIMARY KEY NOT NULL, "text" varchar, "_uuid" varchar );
  CREATE TABLE "_profile_v_version_social_links" ( "_order" integer NOT NULL, "_parent_id" integer NOT NULL, "id" serial PRIMARY KEY NOT NULL, "platform" "enum__profile_v_version_social_links_platform", "url" varchar, "_uuid" varchar );
  CREATE TABLE "_profile_v_version_social_links_locales" ( "label" varchar, "id" serial PRIMARY KEY NOT NULL, "_locale" "_locales" NOT NULL, "_parent_id" integer NOT NULL );
  CREATE TABLE "_profile_v" ( "id" serial PRIMARY KEY NOT NULL, "version_name" varchar, "version__status" "enum__profile_v_version_status" DEFAULT 'draft', "version_updated_at" timestamp(3) with time zone, "version_created_at" timestamp(3) with time zone, "created_at" timestamp(3) with time zone DEFAULT now() NOT NULL, "updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL, "snapshot" boolean, "published_locale" "enum__profile_v_published_locale", "latest" boolean );
  CREATE TABLE "_profile_v_locales" ( "version_job_title" varchar, "version_tagline" varchar, "version_resume_id" integer, "id" serial PRIMARY KEY NOT NULL, "_locale" "_locales" NOT NULL, "_parent_id" integer NOT NULL );
  CREATE TABLE "site_settings" ( "id" serial PRIMARY KEY NOT NULL, "default_language" "enum_site_settings_default_language" DEFAULT 'tr', "language_switcher_position" "enum_site_settings_language_switcher_position" DEFAULT 'top-right', "background_effect" "enum_site_settings_background_effect" DEFAULT 'gradient', "default_section_key" varchar DEFAULT 'about', "_status" "enum_site_settings_status" DEFAULT 'draft', "updated_at" timestamp(3) with time zone, "created_at" timestamp(3) with time zone );
  CREATE TABLE "site_settings_locales" ( "site_title" varchar, "site_description" varchar, "id" serial PRIMARY KEY NOT NULL, "_locale" "_locales" NOT NULL, "_parent_id" integer NOT NULL );
  CREATE TABLE "_site_settings_v" ( "id" serial PRIMARY KEY NOT NULL, "version_default_language" "enum__site_settings_v_version_default_language" DEFAULT 'tr', "version_language_switcher_position" "enum__site_settings_v_version_language_switcher_position" DEFAULT 'top-right', "version_background_effect" "enum__site_settings_v_version_background_effect" DEFAULT 'gradient', "version_default_section_key" varchar DEFAULT 'about', "version__status" "enum__site_settings_v_version_status" DEFAULT 'draft', "version_updated_at" timestamp(3) with time zone, "version_created_at" timestamp(3) with time zone, "created_at" timestamp(3) with time zone DEFAULT now() NOT NULL, "updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL, "snapshot" boolean, "published_locale" "enum__site_settings_v_published_locale", "latest" boolean );
  CREATE TABLE "_site_settings_v_locales" ( "version_site_title" varchar, "version_site_description" varchar, "id" serial PRIMARY KEY NOT NULL, "_locale" "_locales" NOT NULL, "_parent_id" integer NOT NULL );
  ALTER TABLE "users_sessions" ADD CONSTRAINT "users_sessions_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "sections_legacy_anchors" ADD CONSTRAINT "sections_legacy_anchors_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."sections"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "sections_locales" ADD CONSTRAINT "sections_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."sections"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_sections_v_version_legacy_anchors" ADD CONSTRAINT "_sections_v_version_legacy_anchors_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_sections_v"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_sections_v" ADD CONSTRAINT "_sections_v_parent_id_sections_id_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."sections"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_sections_v_locales" ADD CONSTRAINT "_sections_v_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_sections_v"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "experiences_technologies" ADD CONSTRAINT "experiences_technologies_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."experiences"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "experiences_locales" ADD CONSTRAINT "experiences_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."experiences"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_experiences_v_version_technologies" ADD CONSTRAINT "_experiences_v_version_technologies_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_experiences_v"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_experiences_v" ADD CONSTRAINT "_experiences_v_parent_id_experiences_id_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."experiences"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_experiences_v_locales" ADD CONSTRAINT "_experiences_v_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_experiences_v"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "projects_technologies" ADD CONSTRAINT "projects_technologies_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."projects"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "projects" ADD CONSTRAINT "projects_image_id_media_id_fk" FOREIGN KEY ("image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "projects_locales" ADD CONSTRAINT "projects_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."projects"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_projects_v_version_technologies" ADD CONSTRAINT "_projects_v_version_technologies_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_projects_v"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_projects_v" ADD CONSTRAINT "_projects_v_parent_id_projects_id_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."projects"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_projects_v" ADD CONSTRAINT "_projects_v_version_image_id_media_id_fk" FOREIGN KEY ("version_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_projects_v_locales" ADD CONSTRAINT "_projects_v_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_projects_v"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "skill_groups_skills" ADD CONSTRAINT "skill_groups_skills_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."skill_groups"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "skill_groups_locales" ADD CONSTRAINT "skill_groups_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."skill_groups"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_skill_groups_v_version_skills" ADD CONSTRAINT "_skill_groups_v_version_skills_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_skill_groups_v"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_skill_groups_v" ADD CONSTRAINT "_skill_groups_v_parent_id_skill_groups_id_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."skill_groups"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_skill_groups_v_locales" ADD CONSTRAINT "_skill_groups_v_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_skill_groups_v"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "education_locales" ADD CONSTRAINT "education_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."education"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_education_v" ADD CONSTRAINT "_education_v_parent_id_education_id_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."education"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_education_v_locales" ADD CONSTRAINT "_education_v_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_education_v"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "hobbies_locales" ADD CONSTRAINT "hobbies_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."hobbies"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_hobbies_v" ADD CONSTRAINT "_hobbies_v_parent_id_hobbies_id_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."hobbies"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_hobbies_v_locales" ADD CONSTRAINT "_hobbies_v_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_hobbies_v"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."payload_locked_documents"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_users_fk" FOREIGN KEY ("users_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_media_fk" FOREIGN KEY ("media_id") REFERENCES "public"."media"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_sections_fk" FOREIGN KEY ("sections_id") REFERENCES "public"."sections"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_experiences_fk" FOREIGN KEY ("experiences_id") REFERENCES "public"."experiences"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_projects_fk" FOREIGN KEY ("projects_id") REFERENCES "public"."projects"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_skill_groups_fk" FOREIGN KEY ("skill_groups_id") REFERENCES "public"."skill_groups"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_education_fk" FOREIGN KEY ("education_id") REFERENCES "public"."education"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_hobbies_fk" FOREIGN KEY ("hobbies_id") REFERENCES "public"."hobbies"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_preferences_rels" ADD CONSTRAINT "payload_preferences_rels_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."payload_preferences"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_preferences_rels" ADD CONSTRAINT "payload_preferences_rels_users_fk" FOREIGN KEY ("users_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "profile_about_paragraphs" ADD CONSTRAINT "profile_about_paragraphs_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."profile"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "profile_social_links" ADD CONSTRAINT "profile_social_links_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."profile"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "profile_social_links_locales" ADD CONSTRAINT "profile_social_links_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."profile_social_links"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "profile_locales" ADD CONSTRAINT "profile_locales_resume_id_media_id_fk" FOREIGN KEY ("resume_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "profile_locales" ADD CONSTRAINT "profile_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."profile"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_profile_v_version_about_paragraphs" ADD CONSTRAINT "_profile_v_version_about_paragraphs_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_profile_v"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_profile_v_version_social_links" ADD CONSTRAINT "_profile_v_version_social_links_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_profile_v"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_profile_v_version_social_links_locales" ADD CONSTRAINT "_profile_v_version_social_links_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_profile_v_version_social_links"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_profile_v_locales" ADD CONSTRAINT "_profile_v_locales_version_resume_id_media_id_fk" FOREIGN KEY ("version_resume_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_profile_v_locales" ADD CONSTRAINT "_profile_v_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_profile_v"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "site_settings_locales" ADD CONSTRAINT "site_settings_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."site_settings"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_site_settings_v_locales" ADD CONSTRAINT "_site_settings_v_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_site_settings_v"("id") ON DELETE cascade ON UPDATE no action;
  CREATE INDEX "users_sessions_order_idx" ON "users_sessions" USING btree ("_order");
  CREATE INDEX "users_sessions_parent_id_idx" ON "users_sessions" USING btree ("_parent_id");
  CREATE INDEX "users_updated_at_idx" ON "users" USING btree ("updated_at");
  CREATE INDEX "users_created_at_idx" ON "users" USING btree ("created_at");
  CREATE UNIQUE INDEX "users_email_idx" ON "users" USING btree ("email");
  CREATE INDEX "media_updated_at_idx" ON "media" USING btree ("updated_at");
  CREATE INDEX "media_created_at_idx" ON "media" USING btree ("created_at");
  CREATE UNIQUE INDEX "media_filename_idx" ON "media" USING btree ("filename");
  CREATE INDEX "sections_legacy_anchors_order_idx" ON "sections_legacy_anchors" USING btree ("_order");
  CREATE INDEX "sections_legacy_anchors_parent_id_idx" ON "sections_legacy_anchors" USING btree ("_parent_id");
  CREATE INDEX "sections_legacy_anchors_locale_idx" ON "sections_legacy_anchors" USING btree ("_locale");
  CREATE UNIQUE INDEX "sections_key_idx" ON "sections" USING btree ("key");
  CREATE INDEX "sections_order_idx" ON "sections" USING btree ("order");
  CREATE INDEX "sections_updated_at_idx" ON "sections" USING btree ("updated_at");
  CREATE INDEX "sections_created_at_idx" ON "sections" USING btree ("created_at");
  CREATE INDEX "sections__status_idx" ON "sections" USING btree ("_status");
  CREATE INDEX "sections_anchor_idx" ON "sections_locales" USING btree ("anchor","_locale");
  CREATE UNIQUE INDEX "sections_locales_locale_parent_id_unique" ON "sections_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_sections_v_version_legacy_anchors_order_idx" ON "_sections_v_version_legacy_anchors" USING btree ("_order");
  CREATE INDEX "_sections_v_version_legacy_anchors_parent_id_idx" ON "_sections_v_version_legacy_anchors" USING btree ("_parent_id");
  CREATE INDEX "_sections_v_version_legacy_anchors_locale_idx" ON "_sections_v_version_legacy_anchors" USING btree ("_locale");
  CREATE INDEX "_sections_v_parent_idx" ON "_sections_v" USING btree ("parent_id");
  CREATE INDEX "_sections_v_version_version_key_idx" ON "_sections_v" USING btree ("version_key");
  CREATE INDEX "_sections_v_version_version_order_idx" ON "_sections_v" USING btree ("version_order");
  CREATE INDEX "_sections_v_version_version_updated_at_idx" ON "_sections_v" USING btree ("version_updated_at");
  CREATE INDEX "_sections_v_version_version_created_at_idx" ON "_sections_v" USING btree ("version_created_at");
  CREATE INDEX "_sections_v_version_version__status_idx" ON "_sections_v" USING btree ("version__status");
  CREATE INDEX "_sections_v_created_at_idx" ON "_sections_v" USING btree ("created_at");
  CREATE INDEX "_sections_v_updated_at_idx" ON "_sections_v" USING btree ("updated_at");
  CREATE INDEX "_sections_v_snapshot_idx" ON "_sections_v" USING btree ("snapshot");
  CREATE INDEX "_sections_v_published_locale_idx" ON "_sections_v" USING btree ("published_locale");
  CREATE INDEX "_sections_v_latest_idx" ON "_sections_v" USING btree ("latest");
  CREATE INDEX "_sections_v_version_version_anchor_idx" ON "_sections_v_locales" USING btree ("version_anchor","_locale");
  CREATE UNIQUE INDEX "_sections_v_locales_locale_parent_id_unique" ON "_sections_v_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "experiences_technologies_order_idx" ON "experiences_technologies" USING btree ("_order");
  CREATE INDEX "experiences_technologies_parent_id_idx" ON "experiences_technologies" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "experiences_key_idx" ON "experiences" USING btree ("key");
  CREATE INDEX "experiences_order_idx" ON "experiences" USING btree ("order");
  CREATE INDEX "experiences_updated_at_idx" ON "experiences" USING btree ("updated_at");
  CREATE INDEX "experiences_created_at_idx" ON "experiences" USING btree ("created_at");
  CREATE INDEX "experiences__status_idx" ON "experiences" USING btree ("_status");
  CREATE UNIQUE INDEX "experiences_locales_locale_parent_id_unique" ON "experiences_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_experiences_v_version_technologies_order_idx" ON "_experiences_v_version_technologies" USING btree ("_order");
  CREATE INDEX "_experiences_v_version_technologies_parent_id_idx" ON "_experiences_v_version_technologies" USING btree ("_parent_id");
  CREATE INDEX "_experiences_v_parent_idx" ON "_experiences_v" USING btree ("parent_id");
  CREATE INDEX "_experiences_v_version_version_key_idx" ON "_experiences_v" USING btree ("version_key");
  CREATE INDEX "_experiences_v_version_version_order_idx" ON "_experiences_v" USING btree ("version_order");
  CREATE INDEX "_experiences_v_version_version_updated_at_idx" ON "_experiences_v" USING btree ("version_updated_at");
  CREATE INDEX "_experiences_v_version_version_created_at_idx" ON "_experiences_v" USING btree ("version_created_at");
  CREATE INDEX "_experiences_v_version_version__status_idx" ON "_experiences_v" USING btree ("version__status");
  CREATE INDEX "_experiences_v_created_at_idx" ON "_experiences_v" USING btree ("created_at");
  CREATE INDEX "_experiences_v_updated_at_idx" ON "_experiences_v" USING btree ("updated_at");
  CREATE INDEX "_experiences_v_snapshot_idx" ON "_experiences_v" USING btree ("snapshot");
  CREATE INDEX "_experiences_v_published_locale_idx" ON "_experiences_v" USING btree ("published_locale");
  CREATE INDEX "_experiences_v_latest_idx" ON "_experiences_v" USING btree ("latest");
  CREATE UNIQUE INDEX "_experiences_v_locales_locale_parent_id_unique" ON "_experiences_v_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "projects_technologies_order_idx" ON "projects_technologies" USING btree ("_order");
  CREATE INDEX "projects_technologies_parent_id_idx" ON "projects_technologies" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "projects_key_idx" ON "projects" USING btree ("key");
  CREATE INDEX "projects_image_idx" ON "projects" USING btree ("image_id");
  CREATE INDEX "projects_order_idx" ON "projects" USING btree ("order");
  CREATE INDEX "projects_updated_at_idx" ON "projects" USING btree ("updated_at");
  CREATE INDEX "projects_created_at_idx" ON "projects" USING btree ("created_at");
  CREATE INDEX "projects__status_idx" ON "projects" USING btree ("_status");
  CREATE UNIQUE INDEX "projects_locales_locale_parent_id_unique" ON "projects_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_projects_v_version_technologies_order_idx" ON "_projects_v_version_technologies" USING btree ("_order");
  CREATE INDEX "_projects_v_version_technologies_parent_id_idx" ON "_projects_v_version_technologies" USING btree ("_parent_id");
  CREATE INDEX "_projects_v_parent_idx" ON "_projects_v" USING btree ("parent_id");
  CREATE INDEX "_projects_v_version_version_key_idx" ON "_projects_v" USING btree ("version_key");
  CREATE INDEX "_projects_v_version_version_image_idx" ON "_projects_v" USING btree ("version_image_id");
  CREATE INDEX "_projects_v_version_version_order_idx" ON "_projects_v" USING btree ("version_order");
  CREATE INDEX "_projects_v_version_version_updated_at_idx" ON "_projects_v" USING btree ("version_updated_at");
  CREATE INDEX "_projects_v_version_version_created_at_idx" ON "_projects_v" USING btree ("version_created_at");
  CREATE INDEX "_projects_v_version_version__status_idx" ON "_projects_v" USING btree ("version__status");
  CREATE INDEX "_projects_v_created_at_idx" ON "_projects_v" USING btree ("created_at");
  CREATE INDEX "_projects_v_updated_at_idx" ON "_projects_v" USING btree ("updated_at");
  CREATE INDEX "_projects_v_snapshot_idx" ON "_projects_v" USING btree ("snapshot");
  CREATE INDEX "_projects_v_published_locale_idx" ON "_projects_v" USING btree ("published_locale");
  CREATE INDEX "_projects_v_latest_idx" ON "_projects_v" USING btree ("latest");
  CREATE UNIQUE INDEX "_projects_v_locales_locale_parent_id_unique" ON "_projects_v_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "skill_groups_skills_order_idx" ON "skill_groups_skills" USING btree ("_order");
  CREATE INDEX "skill_groups_skills_parent_id_idx" ON "skill_groups_skills" USING btree ("_parent_id");
  CREATE INDEX "skill_groups_skills_locale_idx" ON "skill_groups_skills" USING btree ("_locale");
  CREATE UNIQUE INDEX "skill_groups_key_idx" ON "skill_groups" USING btree ("key");
  CREATE INDEX "skill_groups_order_idx" ON "skill_groups" USING btree ("order");
  CREATE INDEX "skill_groups_updated_at_idx" ON "skill_groups" USING btree ("updated_at");
  CREATE INDEX "skill_groups_created_at_idx" ON "skill_groups" USING btree ("created_at");
  CREATE INDEX "skill_groups__status_idx" ON "skill_groups" USING btree ("_status");
  CREATE UNIQUE INDEX "skill_groups_locales_locale_parent_id_unique" ON "skill_groups_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_skill_groups_v_version_skills_order_idx" ON "_skill_groups_v_version_skills" USING btree ("_order");
  CREATE INDEX "_skill_groups_v_version_skills_parent_id_idx" ON "_skill_groups_v_version_skills" USING btree ("_parent_id");
  CREATE INDEX "_skill_groups_v_version_skills_locale_idx" ON "_skill_groups_v_version_skills" USING btree ("_locale");
  CREATE INDEX "_skill_groups_v_parent_idx" ON "_skill_groups_v" USING btree ("parent_id");
  CREATE INDEX "_skill_groups_v_version_version_key_idx" ON "_skill_groups_v" USING btree ("version_key");
  CREATE INDEX "_skill_groups_v_version_version_order_idx" ON "_skill_groups_v" USING btree ("version_order");
  CREATE INDEX "_skill_groups_v_version_version_updated_at_idx" ON "_skill_groups_v" USING btree ("version_updated_at");
  CREATE INDEX "_skill_groups_v_version_version_created_at_idx" ON "_skill_groups_v" USING btree ("version_created_at");
  CREATE INDEX "_skill_groups_v_version_version__status_idx" ON "_skill_groups_v" USING btree ("version__status");
  CREATE INDEX "_skill_groups_v_created_at_idx" ON "_skill_groups_v" USING btree ("created_at");
  CREATE INDEX "_skill_groups_v_updated_at_idx" ON "_skill_groups_v" USING btree ("updated_at");
  CREATE INDEX "_skill_groups_v_snapshot_idx" ON "_skill_groups_v" USING btree ("snapshot");
  CREATE INDEX "_skill_groups_v_published_locale_idx" ON "_skill_groups_v" USING btree ("published_locale");
  CREATE INDEX "_skill_groups_v_latest_idx" ON "_skill_groups_v" USING btree ("latest");
  CREATE UNIQUE INDEX "_skill_groups_v_locales_locale_parent_id_unique" ON "_skill_groups_v_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "education_key_idx" ON "education" USING btree ("key");
  CREATE INDEX "education_order_idx" ON "education" USING btree ("order");
  CREATE INDEX "education_updated_at_idx" ON "education" USING btree ("updated_at");
  CREATE INDEX "education_created_at_idx" ON "education" USING btree ("created_at");
  CREATE INDEX "education__status_idx" ON "education" USING btree ("_status");
  CREATE UNIQUE INDEX "education_locales_locale_parent_id_unique" ON "education_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_education_v_parent_idx" ON "_education_v" USING btree ("parent_id");
  CREATE INDEX "_education_v_version_version_key_idx" ON "_education_v" USING btree ("version_key");
  CREATE INDEX "_education_v_version_version_order_idx" ON "_education_v" USING btree ("version_order");
  CREATE INDEX "_education_v_version_version_updated_at_idx" ON "_education_v" USING btree ("version_updated_at");
  CREATE INDEX "_education_v_version_version_created_at_idx" ON "_education_v" USING btree ("version_created_at");
  CREATE INDEX "_education_v_version_version__status_idx" ON "_education_v" USING btree ("version__status");
  CREATE INDEX "_education_v_created_at_idx" ON "_education_v" USING btree ("created_at");
  CREATE INDEX "_education_v_updated_at_idx" ON "_education_v" USING btree ("updated_at");
  CREATE INDEX "_education_v_snapshot_idx" ON "_education_v" USING btree ("snapshot");
  CREATE INDEX "_education_v_published_locale_idx" ON "_education_v" USING btree ("published_locale");
  CREATE INDEX "_education_v_latest_idx" ON "_education_v" USING btree ("latest");
  CREATE UNIQUE INDEX "_education_v_locales_locale_parent_id_unique" ON "_education_v_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "hobbies_key_idx" ON "hobbies" USING btree ("key");
  CREATE INDEX "hobbies_order_idx" ON "hobbies" USING btree ("order");
  CREATE INDEX "hobbies_updated_at_idx" ON "hobbies" USING btree ("updated_at");
  CREATE INDEX "hobbies_created_at_idx" ON "hobbies" USING btree ("created_at");
  CREATE INDEX "hobbies__status_idx" ON "hobbies" USING btree ("_status");
  CREATE UNIQUE INDEX "hobbies_locales_locale_parent_id_unique" ON "hobbies_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_hobbies_v_parent_idx" ON "_hobbies_v" USING btree ("parent_id");
  CREATE INDEX "_hobbies_v_version_version_key_idx" ON "_hobbies_v" USING btree ("version_key");
  CREATE INDEX "_hobbies_v_version_version_order_idx" ON "_hobbies_v" USING btree ("version_order");
  CREATE INDEX "_hobbies_v_version_version_updated_at_idx" ON "_hobbies_v" USING btree ("version_updated_at");
  CREATE INDEX "_hobbies_v_version_version_created_at_idx" ON "_hobbies_v" USING btree ("version_created_at");
  CREATE INDEX "_hobbies_v_version_version__status_idx" ON "_hobbies_v" USING btree ("version__status");
  CREATE INDEX "_hobbies_v_created_at_idx" ON "_hobbies_v" USING btree ("created_at");
  CREATE INDEX "_hobbies_v_updated_at_idx" ON "_hobbies_v" USING btree ("updated_at");
  CREATE INDEX "_hobbies_v_snapshot_idx" ON "_hobbies_v" USING btree ("snapshot");
  CREATE INDEX "_hobbies_v_published_locale_idx" ON "_hobbies_v" USING btree ("published_locale");
  CREATE INDEX "_hobbies_v_latest_idx" ON "_hobbies_v" USING btree ("latest");
  CREATE UNIQUE INDEX "_hobbies_v_locales_locale_parent_id_unique" ON "_hobbies_v_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "payload_kv_key_idx" ON "payload_kv" USING btree ("key");
  CREATE INDEX "payload_locked_documents_global_slug_idx" ON "payload_locked_documents" USING btree ("global_slug");
  CREATE INDEX "payload_locked_documents_updated_at_idx" ON "payload_locked_documents" USING btree ("updated_at");
  CREATE INDEX "payload_locked_documents_created_at_idx" ON "payload_locked_documents" USING btree ("created_at");
  CREATE INDEX "payload_locked_documents_rels_order_idx" ON "payload_locked_documents_rels" USING btree ("order");
  CREATE INDEX "payload_locked_documents_rels_parent_idx" ON "payload_locked_documents_rels" USING btree ("parent_id");
  CREATE INDEX "payload_locked_documents_rels_path_idx" ON "payload_locked_documents_rels" USING btree ("path");
  CREATE INDEX "payload_locked_documents_rels_users_id_idx" ON "payload_locked_documents_rels" USING btree ("users_id");
  CREATE INDEX "payload_locked_documents_rels_media_id_idx" ON "payload_locked_documents_rels" USING btree ("media_id");
  CREATE INDEX "payload_locked_documents_rels_sections_id_idx" ON "payload_locked_documents_rels" USING btree ("sections_id");
  CREATE INDEX "payload_locked_documents_rels_experiences_id_idx" ON "payload_locked_documents_rels" USING btree ("experiences_id");
  CREATE INDEX "payload_locked_documents_rels_projects_id_idx" ON "payload_locked_documents_rels" USING btree ("projects_id");
  CREATE INDEX "payload_locked_documents_rels_skill_groups_id_idx" ON "payload_locked_documents_rels" USING btree ("skill_groups_id");
  CREATE INDEX "payload_locked_documents_rels_education_id_idx" ON "payload_locked_documents_rels" USING btree ("education_id");
  CREATE INDEX "payload_locked_documents_rels_hobbies_id_idx" ON "payload_locked_documents_rels" USING btree ("hobbies_id");
  CREATE INDEX "payload_preferences_key_idx" ON "payload_preferences" USING btree ("key");
  CREATE INDEX "payload_preferences_updated_at_idx" ON "payload_preferences" USING btree ("updated_at");
  CREATE INDEX "payload_preferences_created_at_idx" ON "payload_preferences" USING btree ("created_at");
  CREATE INDEX "payload_preferences_rels_order_idx" ON "payload_preferences_rels" USING btree ("order");
  CREATE INDEX "payload_preferences_rels_parent_idx" ON "payload_preferences_rels" USING btree ("parent_id");
  CREATE INDEX "payload_preferences_rels_path_idx" ON "payload_preferences_rels" USING btree ("path");
  CREATE INDEX "payload_preferences_rels_users_id_idx" ON "payload_preferences_rels" USING btree ("users_id");
  CREATE INDEX "payload_migrations_updated_at_idx" ON "payload_migrations" USING btree ("updated_at");
  CREATE INDEX "payload_migrations_created_at_idx" ON "payload_migrations" USING btree ("created_at");
  CREATE INDEX "profile_about_paragraphs_order_idx" ON "profile_about_paragraphs" USING btree ("_order");
  CREATE INDEX "profile_about_paragraphs_parent_id_idx" ON "profile_about_paragraphs" USING btree ("_parent_id");
  CREATE INDEX "profile_about_paragraphs_locale_idx" ON "profile_about_paragraphs" USING btree ("_locale");
  CREATE INDEX "profile_social_links_order_idx" ON "profile_social_links" USING btree ("_order");
  CREATE INDEX "profile_social_links_parent_id_idx" ON "profile_social_links" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "profile_social_links_locales_locale_parent_id_unique" ON "profile_social_links_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "profile__status_idx" ON "profile" USING btree ("_status");
  CREATE INDEX "profile_resume_idx" ON "profile_locales" USING btree ("resume_id","_locale");
  CREATE UNIQUE INDEX "profile_locales_locale_parent_id_unique" ON "profile_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_profile_v_version_about_paragraphs_order_idx" ON "_profile_v_version_about_paragraphs" USING btree ("_order");
  CREATE INDEX "_profile_v_version_about_paragraphs_parent_id_idx" ON "_profile_v_version_about_paragraphs" USING btree ("_parent_id");
  CREATE INDEX "_profile_v_version_about_paragraphs_locale_idx" ON "_profile_v_version_about_paragraphs" USING btree ("_locale");
  CREATE INDEX "_profile_v_version_social_links_order_idx" ON "_profile_v_version_social_links" USING btree ("_order");
  CREATE INDEX "_profile_v_version_social_links_parent_id_idx" ON "_profile_v_version_social_links" USING btree ("_parent_id");
  CREATE UNIQUE INDEX "_profile_v_version_social_links_locales_locale_parent_id_uni" ON "_profile_v_version_social_links_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_profile_v_version_version__status_idx" ON "_profile_v" USING btree ("version__status");
  CREATE INDEX "_profile_v_created_at_idx" ON "_profile_v" USING btree ("created_at");
  CREATE INDEX "_profile_v_updated_at_idx" ON "_profile_v" USING btree ("updated_at");
  CREATE INDEX "_profile_v_snapshot_idx" ON "_profile_v" USING btree ("snapshot");
  CREATE INDEX "_profile_v_published_locale_idx" ON "_profile_v" USING btree ("published_locale");
  CREATE INDEX "_profile_v_latest_idx" ON "_profile_v" USING btree ("latest");
  CREATE INDEX "_profile_v_version_version_resume_idx" ON "_profile_v_locales" USING btree ("version_resume_id","_locale");
  CREATE UNIQUE INDEX "_profile_v_locales_locale_parent_id_unique" ON "_profile_v_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "site_settings__status_idx" ON "site_settings" USING btree ("_status");
  CREATE UNIQUE INDEX "site_settings_locales_locale_parent_id_unique" ON "site_settings_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_site_settings_v_version_version__status_idx" ON "_site_settings_v" USING btree ("version__status");
  CREATE INDEX "_site_settings_v_created_at_idx" ON "_site_settings_v" USING btree ("created_at");
  CREATE INDEX "_site_settings_v_updated_at_idx" ON "_site_settings_v" USING btree ("updated_at");
  CREATE INDEX "_site_settings_v_snapshot_idx" ON "_site_settings_v" USING btree ("snapshot");
  CREATE INDEX "_site_settings_v_published_locale_idx" ON "_site_settings_v" USING btree ("published_locale");
  CREATE INDEX "_site_settings_v_latest_idx" ON "_site_settings_v" USING btree ("latest");
  CREATE UNIQUE INDEX "_site_settings_v_locales_locale_parent_id_unique" ON "_site_settings_v_locales" USING btree ("_locale","_parent_id");`)
}

export async function down({ db, payload: _payload, req: _req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
  DROP TABLE "users_sessions" CASCADE;
  DROP TABLE "users" CASCADE;
  DROP TABLE "media" CASCADE;
  DROP TABLE "sections_legacy_anchors" CASCADE;
  DROP TABLE "sections" CASCADE;
  DROP TABLE "sections_locales" CASCADE;
  DROP TABLE "_sections_v_version_legacy_anchors" CASCADE;
  DROP TABLE "_sections_v" CASCADE;
  DROP TABLE "_sections_v_locales" CASCADE;
  DROP TABLE "experiences_technologies" CASCADE;
  DROP TABLE "experiences" CASCADE;
  DROP TABLE "experiences_locales" CASCADE;
  DROP TABLE "_experiences_v_version_technologies" CASCADE;
  DROP TABLE "_experiences_v" CASCADE;
  DROP TABLE "_experiences_v_locales" CASCADE;
  DROP TABLE "projects_technologies" CASCADE;
  DROP TABLE "projects" CASCADE;
  DROP TABLE "projects_locales" CASCADE;
  DROP TABLE "_projects_v_version_technologies" CASCADE;
  DROP TABLE "_projects_v" CASCADE;
  DROP TABLE "_projects_v_locales" CASCADE;
  DROP TABLE "skill_groups_skills" CASCADE;
  DROP TABLE "skill_groups" CASCADE;
  DROP TABLE "skill_groups_locales" CASCADE;
  DROP TABLE "_skill_groups_v_version_skills" CASCADE;
  DROP TABLE "_skill_groups_v" CASCADE;
  DROP TABLE "_skill_groups_v_locales" CASCADE;
  DROP TABLE "education" CASCADE;
  DROP TABLE "education_locales" CASCADE;
  DROP TABLE "_education_v" CASCADE;
  DROP TABLE "_education_v_locales" CASCADE;
  DROP TABLE "hobbies" CASCADE;
  DROP TABLE "hobbies_locales" CASCADE;
  DROP TABLE "_hobbies_v" CASCADE;
  DROP TABLE "_hobbies_v_locales" CASCADE;
  DROP TABLE "payload_kv" CASCADE;
  DROP TABLE "payload_locked_documents" CASCADE;
  DROP TABLE "payload_locked_documents_rels" CASCADE;
  DROP TABLE "payload_preferences" CASCADE;
  DROP TABLE "payload_preferences_rels" CASCADE;
  DROP TABLE "payload_migrations" CASCADE;
  DROP TABLE "profile_about_paragraphs" CASCADE;
  DROP TABLE "profile_social_links" CASCADE;
  DROP TABLE "profile_social_links_locales" CASCADE;
  DROP TABLE "profile" CASCADE;
  DROP TABLE "profile_locales" CASCADE;
  DROP TABLE "_profile_v_version_about_paragraphs" CASCADE;
  DROP TABLE "_profile_v_version_social_links" CASCADE;
  DROP TABLE "_profile_v_version_social_links_locales" CASCADE;
  DROP TABLE "_profile_v" CASCADE;
  DROP TABLE "_profile_v_locales" CASCADE;
  DROP TABLE "site_settings" CASCADE;
  DROP TABLE "site_settings_locales" CASCADE;
  DROP TABLE "_site_settings_v" CASCADE;
  DROP TABLE "_site_settings_v_locales" CASCADE;
  DROP TYPE "public"."_locales";
  DROP TYPE "public"."enum_sections_type";
  DROP TYPE "public"."enum_sections_status";
  DROP TYPE "public"."enum__sections_v_version_type";
  DROP TYPE "public"."enum__sections_v_version_status";
  DROP TYPE "public"."enum__sections_v_published_locale";
  DROP TYPE "public"."enum_experiences_status";
  DROP TYPE "public"."enum__experiences_v_version_status";
  DROP TYPE "public"."enum__experiences_v_published_locale";
  DROP TYPE "public"."enum_projects_status";
  DROP TYPE "public"."enum__projects_v_version_status";
  DROP TYPE "public"."enum__projects_v_published_locale";
  DROP TYPE "public"."enum_skill_groups_skills_color_key";
  DROP TYPE "public"."enum_skill_groups_icon_key";
  DROP TYPE "public"."enum_skill_groups_color_key";
  DROP TYPE "public"."enum_skill_groups_status";
  DROP TYPE "public"."enum__skill_groups_v_version_skills_color_key";
  DROP TYPE "public"."enum__skill_groups_v_version_icon_key";
  DROP TYPE "public"."enum__skill_groups_v_version_color_key";
  DROP TYPE "public"."enum__skill_groups_v_version_status";
  DROP TYPE "public"."enum__skill_groups_v_published_locale";
  DROP TYPE "public"."enum_education_status";
  DROP TYPE "public"."enum__education_v_version_status";
  DROP TYPE "public"."enum__education_v_published_locale";
  DROP TYPE "public"."enum_hobbies_icon_key";
  DROP TYPE "public"."enum_hobbies_status";
  DROP TYPE "public"."enum__hobbies_v_version_icon_key";
  DROP TYPE "public"."enum__hobbies_v_version_status";
  DROP TYPE "public"."enum__hobbies_v_published_locale";
  DROP TYPE "public"."enum_profile_social_links_platform";
  DROP TYPE "public"."enum_profile_status";
  DROP TYPE "public"."enum__profile_v_version_social_links_platform";
  DROP TYPE "public"."enum__profile_v_version_status";
  DROP TYPE "public"."enum__profile_v_published_locale";
  DROP TYPE "public"."enum_site_settings_default_language";
  DROP TYPE "public"."enum_site_settings_language_switcher_position";
  DROP TYPE "public"."enum_site_settings_background_effect";
  DROP TYPE "public"."enum_site_settings_status";
  DROP TYPE "public"."enum__site_settings_v_version_default_language";
  DROP TYPE "public"."enum__site_settings_v_version_language_switcher_position";
  DROP TYPE "public"."enum__site_settings_v_version_background_effect";
  DROP TYPE "public"."enum__site_settings_v_version_status";
  DROP TYPE "public"."enum__site_settings_v_published_locale";`)
}
